'use client';

import {useState} from 'react';
import LeagueConfigFields,{panel,field,primary} from './LeagueConfigFields';

export default function CommissionerPanel({league,act,busy}:{league:any;act:(action:string,input?:any)=>Promise<void>;busy:boolean}) {
 const [form,setForm]=useState({...league.config,name:league.name});
 const [deadline,setDeadline]=useState('');const [confirmation,setConfirmation]=useState('');
 const [startWeek,setStartWeek]=useState(league.activeWeek);const [season,setSeason]=useState(league.season+1);
 const owner=league.ownerId===league.me;const survivor=league.config.format==='survivor';
 return <div className="space-y-5">
  <section className={panel}><h2 className="text-xl font-bold mb-4">League rules</h2><dl className="grid sm:grid-cols-2 gap-4 text-sm">
   <div><dt className="text-slate-500">Format</dt><dd>{survivor?'Survivor':'Straight Pick’em'}</dd></div><div><dt className="text-slate-500">Commissioner</dt><dd>{league.commissioner}</dd></div><div><dt className="text-slate-500">Co-owners</dt><dd>{league.coOwners?.length?league.coOwners.map((co:any)=>co.name).join(', '):'None yet'}</dd></div>
   <div><dt className="text-slate-500">Deadlines</dt><dd>{league.config.deadlineMode==='first-game'?'All picks lock at the first kickoff':'Each game locks at kickoff'}</dd></div>
   {survivor?<><div><dt className="text-slate-500">Lives per person</dt><dd>{league.config.maxEntries}</dd></div><div><dt className="text-slate-500">Double-pick weeks</dt><dd>{league.config.doublePickWeeks.join(', ')||'None'}</dd></div><div><dt className="text-slate-500">Tied games</dt><dd>{league.config.tiesLose?'Eliminate the life':'Life survives'}</dd></div></>:<><div><dt className="text-slate-500">Season record</dt><dd>One record per player</dd></div><div><dt className="text-slate-500">Standings tiebreaker</dt><dd>{league.config.tiebreaker==='correct-picks'?'Most correct picks':'Shared rank'}</dd></div></>}
  </dl><p className="text-slate-400 text-sm mt-5">{survivor?'Teams cannot be reused by the same life. Missing a required pick eliminates that life once the week is final.':'Pick every game each week. Correct picks build each player’s season record; missed and tied games count as zero.'} Previous weeks remain available to view, but cannot be edited.</p>{league.deadlines?.[league.activeWeek]&&<p className="mt-3 text-amber-300">Custom deadline: {new Date(league.deadlines[league.activeWeek]).toLocaleString()}</p>}</section>
  {owner&&<>
   <form className={`${panel} space-y-5`} onSubmit={e=>{e.preventDefault();void act('settings',form);}}><h2 className="text-xl font-bold">Commissioner settings</h2><LeagueConfigFields value={form} onChange={setForm} existing/><button disabled={busy} className={primary}>Save league settings</button></form>
   <form className={`${panel} space-y-4`} onSubmit={e=>{e.preventDefault();void act('deadline',{week:league.activeWeek,deadline:new Date(deadline).toISOString()});}}><h2 className="text-xl font-bold">Set this week’s earlier deadline</h2><p className="text-sm text-slate-400">Set it before anyone submits picks and no later than the first kickoff. Times use your device’s time zone.</p><label className="block">Week {league.activeWeek} deadline<input className={field} type="datetime-local" required value={deadline} onChange={e=>setDeadline(e.target.value)}/></label><button disabled={busy} className={primary}>Set deadline</button></form>
   {survivor&&league.season===2026&&<form className={`${panel} space-y-4 border-amber-800`} onSubmit={e=>{e.preventDefault();const confirmed=window.prompt(`Type ${league.name} to confirm the Week 1 historical backfill.`);if(confirmed)void act('backfill',{confirmation:confirmed});}}><h2 className="text-xl font-bold text-amber-200">Backfill Week 1</h2><p className="text-sm text-slate-400">Use this once for the launch league. It creates Lives 1–8 and records the agreed Week 1 results before opening Week 2.</p><button disabled={busy} className={primary}>Record historical Week 1 picks</button></form>}
   <section className={panel}><h2 className="text-xl font-bold">Invite co-owners</h2><p className="text-sm text-slate-400 mt-2">Share this league’s invite link or code. New players can join as members with their own entries, or select an existing player to co-own their entries. Co-owners make picks for their selected player, but only you can change rules, deadlines, or reset the league.</p></section>
   <details className="rounded-2xl border border-amber-900 p-6"><summary className="text-amber-300 font-bold cursor-pointer">Reset league or start a new season</summary><p className="text-sm text-slate-400 mt-4">These actions archive the current picks, then clear the active competition. Co-owners remain in the league.</p><label className="block mt-4">Starting week<select className={field} value={startWeek} onChange={e=>setStartWeek(Number(e.target.value))}>{Array.from({length:18},(_,i)=>i+1).map(w=><option key={w} value={w}>Week {w}</option>)}</select></label><label className="block mt-4">Type “{league.name}” to confirm<input className={field} value={confirmation} onChange={e=>setConfirmation(e.target.value)}/></label><button type="button" className={`${primary} mt-4`} disabled={busy||confirmation!==league.name} onClick={()=>act('reset',{confirmation,startWeek})}>Archive picks & reset this league</button><label className="block mt-6">New season<input type="number" className={field} value={season} min={league.season+1} max={2030} onChange={e=>setSeason(Number(e.target.value))}/></label><button type="button" className={`${primary} mt-4`} disabled={busy||confirmation!==league.name} onClick={()=>act('rollover',{confirmation,startWeek,season})}>Archive season & start new season</button></details>
  </>}
  <section className={panel}><h2 className="font-bold text-xl mb-3">Recent league activity</h2><ul className="space-y-2 text-sm text-slate-400">{league.audit.slice(-15).reverse().map((a:any,i:number)=><li key={i}>{a.action} · {league.members.find((m:any)=>m.userId===a.actor)?.name||'Former member'} · {new Date(a.at).toLocaleString()}</li>)}{!league.audit.length&&<li>No changes recorded yet.</li>}</ul></section>
 </div>;
}
